// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using EhautX.Model;
using Foundation;

namespace EhautX.View
{
    public partial class NetworkPrefsController : NSViewController
	{
        public static AppDelegate App => (AppDelegate)NSApplication.SharedApplication.Delegate;

        [Export("Preferences")]
        public AppPreferences Preferences => App.Preferences;

        public NetworkPrefsController (IntPtr handle) : base (handle)
		{
		}
	}
}
